package com.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dao.GroupDetalDO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GroupDetal.
*/
public class GroupDetalDao extends AbstractDao<GroupDetalDO, String> {

    public static final String TABLENAME = "GroupDetal";

    /**
     * Properties of entity GroupDetalDO.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Approval = new Property(0, Boolean.class, "approval", false, "APPROVAL");
        public final static Property Canadd = new Property(1, String.class, "canadd", false, "CANADD");
        public final static Property Desc = new Property(2, String.class, "desc", false, "DESC");
        public final static Property Gphoto = new Property(3, String.class, "gphoto", false, "GPHOTO");
        public final static Property Groupid = new Property(4, String.class, "groupid", true, "GROUPID");
        public final static Property Groupname = new Property(5, String.class, "groupname", false, "GROUPNAME");
        public final static Property Maxusers = new Property(6, Integer.class, "maxusers", false, "MAXUSERS");
        public final static Property Memnum = new Property(7, Integer.class, "memnum", false, "MEMNUM");
        public final static Property Owner = new Property(8, String.class, "owner", false, "OWNER");
        public final static Property Payfor = new Property(9, Integer.class, "payfor", false, "PAYFOR");
        public final static Property Validt = new Property(10, String.class, "validt", false, "VALIDT");
        public final static Property Visble = new Property(11, String.class, "visble", false, "VISBLE");
        public final static Property Istoll = new Property(12, String.class, "istoll", false, "ISTOLL");
    };


    public GroupDetalDao(DaoConfig config) {
        super(config);
    }
    
    public GroupDetalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GroupDetal' (" + //
                "'APPROVAL' INTEGER," + // 0: approval
                "'CANADD' TEXT," + // 1: canadd
                "'DESC' TEXT," + // 2: desc
                "'GPHOTO' TEXT," + // 3: gphoto
                "'GROUPID' TEXT PRIMARY KEY NOT NULL ," + // 4: groupid
                "'GROUPNAME' TEXT," + // 5: groupname
                "'MAXUSERS' INTEGER," + // 6: maxusers
                "'MEMNUM' INTEGER," + // 7: memnum
                "'OWNER' TEXT," + // 8: owner
                "'PAYFOR' INTEGER," + // 9: payfor
                "'VALIDT' TEXT," + // 10: validt
                "'VISBLE' TEXT," + // 11: visble
                "'ISTOLL' TEXT);"); // 12: istoll
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GroupDetal'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GroupDetalDO entity) {
        stmt.clearBindings();
 
        Boolean approval = entity.getApproval();
        if (approval != null) {
            stmt.bindLong(1, approval ? 1l: 0l);
        }
 
        String canadd = entity.getCanadd();
        if (canadd != null) {
            stmt.bindString(2, canadd);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(3, desc);
        }
 
        String gphoto = entity.getGphoto();
        if (gphoto != null) {
            stmt.bindString(4, gphoto);
        }
 
        String groupid = entity.getGroupid();
        if (groupid != null) {
            stmt.bindString(5, groupid);
        }
 
        String groupname = entity.getGroupname();
        if (groupname != null) {
            stmt.bindString(6, groupname);
        }
 
        Integer maxusers = entity.getMaxusers();
        if (maxusers != null) {
            stmt.bindLong(7, maxusers);
        }
 
        Integer memnum = entity.getMemnum();
        if (memnum != null) {
            stmt.bindLong(8, memnum);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(9, owner);
        }
 
        Integer payfor = entity.getPayfor();
        if (payfor != null) {
            stmt.bindLong(10, payfor);
        }
 
        String validt = entity.getValidt();
        if (validt != null) {
            stmt.bindString(11, validt);
        }
 
        String visble = entity.getVisble();
        if (visble != null) {
            stmt.bindString(12, visble);
        }
 
        String istoll = entity.getIstoll();
        if (istoll != null) {
            stmt.bindString(13, istoll);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4);
    }    

    /** @inheritdoc */
    @Override
    public GroupDetalDO readEntity(Cursor cursor, int offset) {
        GroupDetalDO entity = new GroupDetalDO( //
            cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0, // approval
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // canadd
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // desc
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gphoto
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // groupid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // groupname
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // maxusers
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // memnum
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // owner
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // payfor
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // validt
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // visble
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // istoll
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GroupDetalDO entity, int offset) {
        entity.setApproval(cursor.isNull(offset + 0) ? null : cursor.getShort(offset + 0) != 0);
        entity.setCanadd(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDesc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGphoto(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGroupid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGroupname(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMaxusers(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setMemnum(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setOwner(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPayfor(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setValidt(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setVisble(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIstoll(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(GroupDetalDO entity, long rowId) {
        return entity.getGroupid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(GroupDetalDO entity) {
        if(entity != null) {
            return entity.getGroupid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
