package com.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table InviteMessage.
 */
public class InviteMessageDO {

    private Long id;
    private String from;
    private Long time;
    private String reason;
    private Integer status;
    private Integer unreadCount;
    private String groupId;
    private String groupName;
    private String headphoto;

    public InviteMessageDO() {
    }

    public InviteMessageDO(Long id) {
        this.id = id;
    }

    public InviteMessageDO(Long id, String from, Long time, String reason, Integer status, Integer unreadCount, String groupId, String groupName, String headphoto) {
        this.id = id;
        this.from = from;
        this.time = time;
        this.reason = reason;
        this.status = status;
        this.unreadCount = unreadCount;
        this.groupId = groupId;
        this.groupName = groupName;
        this.headphoto = headphoto;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(Integer unreadCount) {
        this.unreadCount = unreadCount;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getHeadphoto() {
        return headphoto;
    }

    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto;
    }

}
