package com.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table User.
 */
public class UserDO {

    private Long id;
    private Integer unreadMsgCount;
    private String header;
    private String avatar;
    private String type;

    public UserDO() {
    }

    public UserDO(Long id) {
        this.id = id;
    }

    public UserDO(Long id, Integer unreadMsgCount, String header, String avatar, String type) {
        this.id = id;
        this.unreadMsgCount = unreadMsgCount;
        this.header = header;
        this.avatar = avatar;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUnreadMsgCount() {
        return unreadMsgCount;
    }

    public void setUnreadMsgCount(Integer unreadMsgCount) {
        this.unreadMsgCount = unreadMsgCount;
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
